### ISSUE TITLE
Error processing bootstrap-settings.json: Surprising path

### ISSUE THREAD

**Issue by Doeke** [huttonr/bootstrap4#2]
I'm getting the following error after adding bootstrap4 to my local package's dependencies and creating an empty bootstrap-settings.json file:

```
=> Errors prevented startup:

   While processing files with huttonr:bootstrap4 (for target web.browser):
...
   Surprising path: /packages/foo/client/bootstrap-settings.json
   at toDosPath
...
   at Object.basename
...
   at plugin/bootstrap4.js:57:21
```

Looks like the line `path.basename(file.getDisplayPath());` fails, but "Surprising path" isn't very helpful. This is on windows, by the way. Maybe a work-around that doesn't use path.basename is needed? Let me know if I can help.

**Comment by huttonr** [comment]
This is a Windows path error. Will fix it shortly.  See https://github.com/huttonr/bootstrap3/pull/3.

**Comment by huttonr** [comment]
https://github.com/huttonr/bootstrap4/issues/4
