### ISSUE TITLE
Update bootstrap4 package with changes made in bootstrap3 package

### ISSUE THREAD

**Issue by huttonr** [huttonr/bootstrap4#4]
[huttonr:bootstrap3](https://github.com/huttonr/bootstrap3) contains updates and bug fixes that need to be applied to this package as well.

**Comment by twastvedt** [comment]
Is there any workaround to get working on Windows until this is closed, or is this package currently simply unusable on Windows? Thanks!

**Comment by huttonr** [comment]
The Windows issue should now be fixed with 42c9df08a32272f004991868c153e04432da4586

**Comment by huttonr** [comment]
There were still some issues with Windows and binary builds due to a change in the sass package that was being used.  This change was reverted and 1042659aeaf22214e0f8ac3cba239935004a9a55 should now fully solve the windows builds.

There still remains adding in all of the features that are now in [huttonr:bootstrap3](https://github.com/huttonr/bootstrap3).

**Comment by huttonr** [comment]
Added most of the features from huttonr:bootstrap3.

77769e910e2b22269360e1662c6aece2fef255a6
