### ISSUE TITLE
Trouble minifying bootstrap on Meteor

### ISSUE THREAD

**Issue by shmakes** [huttonr/bootstrap4#6]
I apologize in advance, as this is likely not specific to this package as I have the same problem with your bootstrap3 package as well as the twbs/bootstrap package, but I am lost for a solution.

Any time I add one of these bootstrap packages and do a "meteor run --production", the minification fails. If I remove bootstrap it is fine.  

Any ideas or suggestions?

=> Started proxy.  
=> Started MongoDB.  
=> Errors prevented startup:                  

   While minifying app code:
   /home/ss/.meteor/packages/standard-minifiers/.1.0.2.1bzej1y++os+web.browser+web.cordova/plugin.minifyStd.os/npm/minifiers/node_modules/uglify-js/lib/parse.js:196:18: Unexpected token: punc ())
   at new JS_Parse_Error (/home/ss/.meteor/packages/standard-minifiers/.1.0.2.1bzej1y++os+web.browser+web.cordova/plugin.minifyStd.os/npm/minifiers/node_modules/uglify-js/lib/parse.js:196:18)

**Comment by huttonr** [comment]
This may have fixed it: 5cabac0b23a4c4b238caec17ef245ea55e74684e

Try huttonr:bootstrap4@4.0.0_11

**Please let me know.**

**Comment by shmakes** [comment]
That works!
Thank you so much!
